#!/usr/bin/env php
<?php
if (PHP_SAPI !== 'cli') {
    echo 'jtcron must be used as console application';
    exit(1);
}

//define( 'WP_USE_THEMES', false );
define('WP_USE_EXT_MYSQL', false);
require_once( './wp-load.php' );
require_once( ABSPATH . 'wp-admin/includes/plugin.php' );

if (!is_plugin_active('jtcron/jtcron.php')) {
    echo 'JtCron plugin is not active';
    exit(1);
}

use JtCron\Model\Cron;

$runner = new Cron();
$runner->run();